config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # root to: 'repos#index'
  root to: 'repos#home'

  get 'index', to: 'repos#index', as: 'index'
  get 'homepage', to: 'repos#home', as: 'homepage'

  resources :repos, only: [:show]

  post 'repos', to: 'users/repos#create', as: 'repos'
  get 'repos/:id/edit', to:'users/repos#edit', as: 'edit_repo'
  patch 'repos/:id', to: 'users/repos#update'
  put 'repos/:id', to: 'users/repos#update'
  delete 'repos/:id', to: 'users/repos#destroy'

  get 'add_repos', to: 'users/repos#add_repo', as: 'add_repos'


  scope ':username' do
    get 'my-repos', to: 'users/repos#my_repos_index', as: 'my_repos'
    get 'my-collaborations', to: 'users/repos#my_collaborations_index', as: 'my_collaborations'
    post 'my-first-repo', to: 'users/repos#my_first_repo', as: 'my_first_repo'
  end

  # delete 'collaborations/:repo_id/:user_id', to: 'collaborations#destroy', as: 'end_collaboration'
  delete 'collaborations/:repo_id', to: 'collaborations#destroy', as: 'end_collaboration'

  # post 'collaborations', to: 'collaborations#create', as: 'collaborations'
  post 'collaborations/:repo_id', to: 'collaborations#create', as: 'collaborations'

  post 'collaborations/:repo_id/:user_id', to: 'collaborations#update', as: 'confirm_collaboration'



end

app/models/repo.rb
class Repo < ApplicationRecord

  belongs_to :user

  has_many :collaborations
  has_many :users, through: :collaborations

  include PgSearch

  pg_search_scope :global_search,
    against: [[:name, 'A'], [:description, 'B']],
    associated_against: {
      user: [[:name, 'C']]
    },
    using: {
      tsearch: { prefix: true }
  }

end

app/models/user.rb
require 'json'
require 'open-uri'

class User < ApplicationRecord
  has_many :collaborations, dependent: :destroy
  has_many :repos, through: :collaborations, dependent: :destroy
  # after_create :create_user_repos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.token = auth.credentials.token
      user.avatar = auth.info.image
      user.name = auth.info.name
      user.nickname = auth.info.nickname
      user.github = auth.info.urls.GitHub
      user.repos_url = auth[:extra].raw_info.repos_url
  end
end

# def create_user_repos
#     url = u.repos_url
#     repos_serialized = open(url).read
#     repos = JSON.parse(repos_serialized)

#     repos.each do |repo|
#       repository = Repo.new()
#       repository.name = repo['name']
#       repository.description = repo['description']
#       repository.user_id = u.id
#       repository.save
#     end
#   end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @search_results = false
    if params[:query].present?
      @search_results = true
      # @collaborations = Collaboration.global_search(params[:query])
      @repos = Repo.global_search(params[:query])
    else
      @repos = Repo.all
    end
  end

  def show
    @repo = Repo.find(params[:id])

    # Temporary variable that saves all accepted collaborations
    collabs = @repo.collaborations.where(accepted: true)

    # Variable that saves all collaborations (accepted or pending)
    @all_collabs = @repo.collaborations

    # Variable that saves users that are acceptance pending
    @pending_users = @all_collabs.where(accepted: false).map(&:user)

    # Variable that saves all the users that have a collaboration request: approved or not
    @all_users = @all_collabs.map(&:user)

    # Variable that saves only the users whose collaboration request has been approved
    @users = collabs.map(&:user)
  end

  def home
    @repos = Repo.all
  end
end

app/controllers/user/repos_controller.rb
class User::ReposController < ApplicationController
  def my_repos_index
  end

  def my_collaborations_index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)

    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/repos_controller.rb
class Users::ReposController < ApplicationController
  def my_repos_index
    @repos = Repo.where(user_id: current_user.id)

    if @repos.empty?
      my_first_repo
      render 'my_first_repo'
    else
      render 'users/repos/my_repos_index'
    end
  end

  def my_first_repo
    @repo = Repo.new

    url = current_user.repos_url
    repos_serialized = open(url + "?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}").read
    repos = JSON.parse(repos_serialized)

    @new_repos = repos.map do |repo|
      repository = Repo.new()
      repository.name = repo['name']
      repository.description = repo['description']
      repository
    end
  end

  def add_repo
    url = current_user.repos_url
    repos_serialized = open(url + "?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}").read
    repos = JSON.parse(repos_serialized)

    @new_repos = []
    repos.each do |repo|
      unless Repo.find_by_name(repo['name'])
        repository = Repo.new()
        repository.name = repo['name']
        repository.description = repo['description']
        @new_repos << repository
      end
    end
    render 'my_first_repo'
  end

  def my_collaborations_index
    @collabs = current_user.collaborations
    @collab_repos = @collabs.map(&:repo)
  end

  def create
    repo_args(first_repos_index).each do |args|
      repo = Repo.new(args)
      repo.user = current_user
      repo.save
    end
    redirect_to my_repos_path(current_user)
  end

  def update
  end

  def destroy
    Repo.find(params[:id]).destroy
    redirect_to my_repos_path(current_user)
  end

  private

  def first_repos_index
    params.keys.grep(/checkbox_/).map { |x| x[/_.+/][1..-1]  }
  end

  def repo_args(index_list)
    index_list.map do |index|
      {
        name: params["name_#{index}"],
        description: params["description_#{index}"]
      }
    end
  end
end

app/views/users/repos/my_collaborations_index.html.erb
<div class="wrapper-main">
    <!-- Search form -->
  <input class="form-control" type="text" placeholder="Search" aria-label="Search">

  <% @collabs.each do |collab|%>
    <%= render 'components/repos_list', repo: collab.repo, collab: collab %>
  <% end %>

</div>

app/views/users/repos/my_first_repo.html.erb
<div id="first-repo" >
  <div class="first-repo-wraper">
    <div class="form-group">
      <h1>Share your first repository!</h1>
    </div>
    <div>
      <form id="first" action=<%= repos_path %> method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <% @new_repos.each_with_index do |repo, index| %>
          <div class="repo">
            <input type="checkbox" class="form-check-input" name=<%="checkbox_#{index}"%> value='true'>
            <label for="<%= repo.name %>"><%= repo.name %></label>

            <p class="first-input-hiden"> Name:</p><input class="first-input-hiden form-control" type="text" name=<%="name_#{index}"%> value='<%= repo.name %>'><br>

            <p class="first-input-hiden"> Description:</p>

            <textarea class="first-input-hiden first-input-description form-control" name=<%="description_#{index}"%> form_id="first" rows="4" cols="50"><%= repo.description %>
            </textarea><br>
          </div>
        <% end %>

        <button type="submit" class=“btn btn-danger”>Share selected Repos!</button>
      </form>

    </div>
    <div class="new-post-buttons">
    </div>
  </div>
</div>

app/views/users/repos/my_repos_index.html.erb
<div class="wrapper-main">
  <%= render 'components/search-bar' %>
  
  <% if @repos.empty? %>
    <div id="first-repo" >
      <div class="first-repo-wraper">
        <div class="form-group">
          <h1>Share your first repository!</h1>
        </div>
        <div class="form-wrapper">
          <form>
            <% @new_repos.each do |repo| %>

              <div class="repo">

                <input type="checkbox" name='<%= repo.name %>' value="o que quero receber" class="form-check-input">
                <label for="<%= repo.name %>"><%= repo.name %></label>

                <p class="first-input-hiden"> Name:</p><input class="first-input-hiden form-control" type="text" name="name" value='<%= repo.name %>'><br>

                <p class="first-input-hiden"> Description:</p><input class="first-input-hiden first-input-description form-control" type="text" name="description" value='<%= repo.description %>'><br>

              </div>

            <% end %>
            <button type="submit" class="btn btn-primary">Share all selected</button>
          </form>
        </div>
      </div>
    </div>

  <% else %>

    <!-- Search form -->

  <%= link_to 'Add repositories', add_repos_path, :class => "btn btn-success" %>

  <% @repos.each do |repo|%>
    <%= render 'components/repos_list', repo: repo %>
  <% end %>
</div>