config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # root to: 'repos#index'
  root to: 'repos#home'

  get 'index', to: 'repos#index', as: 'index'
  get 'homepage', to: 'repos#home', as: 'homepage'

  resources :repos, only: [:show]

  post 'repos', to: 'users/repos#create', as: 'repos'
  get 'repos/:id/edit', to:'users/repos#edit', as: 'edit_repo'
  patch 'repos/:id', to: 'users/repos#update'
  put 'repos/:id', to: 'users/repos#update'
  delete 'repos/:id', to: 'users/repos#destroy'

  get 'add_repos', to: 'users/repos#add_repo', as: 'add_repos'


  scope ':username' do
    get 'my-repos', to: 'users/repos#my_repos_index', as: 'my_repos'
    get 'my-collaborations', to: 'users/repos#my_collaborations_index', as: 'my_collaborations'
    post 'my-first-repo', to: 'users/repos#my_first_repo', as: 'my_first_repo'
  end

  # delete 'collaborations/:repo_id/:user_id', to: 'collaborations#destroy', as: 'end_collaboration'
  delete 'collaborations/:repo_id', to: 'collaborations#destroy', as: 'end_collaboration'

  # post 'collaborations', to: 'collaborations#create', as: 'collaborations'
  post 'collaborations/:repo_id', to: 'collaborations#create', as: 'collaborations'

  post 'collaborations/:repo_id/:user_id', to: 'collaborations#update', as: 'confirm_collaboration'



end

app/views/layouts/_footer.html.erb
<div class="footer-wrapper">
  <div class="social">
    <i class="fab fa-github-square"></i>
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-twitter-square"></i>
  </div>
  <div class="all-rights">
    <p>© 2018 OScar. All Rights Reserved.</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="header">
  <a href=<%= homepage_path %>><div id="logo" style="background-image: url(<%= asset_path('logo.png')%>);">
  </div></a>

  <div class="header-content">
    <ul class="header-navigation">
      <li><%= link_to( "home", homepage_path) %></li>
      <% if !user_signed_in? %>
        <li><%= link_to( "sign in", user_github_omniauth_authorize_path) %></li>
      <% else %>
        <li><%= link_to( "my repositories", my_repos_path(current_user)) %></li>
        <li><%= link_to( "my collaborations", my_collaborations_path(current_user)) %></li>
        <li><%= link_to( "sign out") %></li>
      <% end %>
    </ul>

  </div>

  <% if !user_signed_in? %>
    <div id="avatar" style="background-image: linear-gradient(-45deg, rgba(150,150,150,0.3) 0%, rgba(56,53,48,0.3) 33%, rgba(77,72,61,0.3) 51%, rgba(56,53,48,0.3) 93%, rgba(66,63,54,0.3) 100%), url(<%= asset_path('default_user.png')%>);">
    </div>
  <% else %>
    <div id="avatar" style="background-image: linear-gradient(-45deg, rgba(150,150,150,0.3) 0%, rgba(56,53,48,0.3) 33%, rgba(77,72,61,0.3) 51%, rgba(56,53,48,0.3) 93%, rgba(66,63,54,0.3) 100%), url(<%= current_user.avatar %>);">
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>OScar - Collaborative highway</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow|PT+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render "layouts/footer" %>
  </body>

</html>